/*
 * The contents of this file are subject to the terms of the Common Development
 * and Distribution License (the License). You may not use this file except in
 * compliance with the License.
 *
 * You can obtain a copy of the License at http://rachota.sourceforge.net/license.txt.
 *
 *
 * When distributing Covered Code, include this CDDL Header Notice in each file
 * and include the License file at http://rachota.sourceforge.net/license.txt.
 * If applicable, add the following below the CDDL Header, with the fields
 * enclosed by brackets [] replaced by your own identifying information:
 * "Portions Copyrighted [year] [name of copyright owner]"
 * The Original Software is Rachota.
 * The Initial Developer of the Original Software is Jiri Kovalsky
 * Portions created by Jiri Kovalsky are Copyright (C) 2010
 * All Rights Reserved.
 *
 * Contributor(s): Jiri Kovalsky
 * Created on Mar 18, 2010, 8:11:35 PM
 * WizardStep.java
 */

package org.cesilko.rachota.gui;

import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

public abstract class WizardStep extends javax.swing.JPanel implements PropertyChangeListener {

    /** Creates new form WizardStep */
    public WizardStep(GenericWizard wizard, String description) {
        this.description = description;
        initComponents();
        addPropertyChangeListener(wizard);
        wizard.addWizardStep(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /* Returns description of this wizard step.
     * @return Description of this wizard step.
     */
    public String getDescription() {
        return description;
    }

    /** Returns font that should be used for all widgets in this component
     * based on the language preferences specified by user.
     * @return Font to be used in this component.
     */
    @Override
    public java.awt.Font getFont() {
        return Tools.getFont();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /** Description of this wizard step. */
    protected String description;

    /** Method called when property of some other wizard step changed.
     * @param evt Event that generated this call.
     */
    abstract public void propertyChange(PropertyChangeEvent evt);

    /** Returns whether everything is set correctly in the wizard step.
     * @return True if wizard step is set correctly.
     */
    abstract protected boolean isSetCorrectly();

    /** Method to set focus to the initial component. */
    abstract protected void setFocus();
}
